spring:
  webflux:
    base-path: /rective-flashcards
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://rective-flashcards:root@db:27017/rective-flashcards?authSource=admin
  mail:
    host: mailcatcher
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25

rective-flashcards:
  mail:
    sender: Reactive Flashcards <noreply@reactiveflashcards.com.br>
retry-config:
  max-retries: 3
  min-duration: 1

http-client:
  response-timeout: 3000
  read-timeout: 3000

deck-api:
  base-url: external:3000
  auth-resource: auth
  decks-resource: decks